# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/parallels/coin_toss

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/parallels/coin_toss

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parallels/coin_toss/CMakeFiles /home/parallels/coin_toss/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parallels/coin_toss/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cointoss

# Build rule for target.
cointoss: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cointoss
.PHONY : cointoss

# fast build rule for target.
cointoss/fast:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/build
.PHONY : cointoss/fast

GF2_8LookupTable.o: GF2_8LookupTable.cpp.o

.PHONY : GF2_8LookupTable.o

# target to build an object file
GF2_8LookupTable.cpp.o:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/GF2_8LookupTable.cpp.o
.PHONY : GF2_8LookupTable.cpp.o

GF2_8LookupTable.i: GF2_8LookupTable.cpp.i

.PHONY : GF2_8LookupTable.i

# target to preprocess a source file
GF2_8LookupTable.cpp.i:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/GF2_8LookupTable.cpp.i
.PHONY : GF2_8LookupTable.cpp.i

GF2_8LookupTable.s: GF2_8LookupTable.cpp.s

.PHONY : GF2_8LookupTable.s

# target to generate assembly for a file
GF2_8LookupTable.cpp.s:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/GF2_8LookupTable.cpp.s
.PHONY : GF2_8LookupTable.cpp.s

TemplateField.o: TemplateField.cpp.o

.PHONY : TemplateField.o

# target to build an object file
TemplateField.cpp.o:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/TemplateField.cpp.o
.PHONY : TemplateField.cpp.o

TemplateField.i: TemplateField.cpp.i

.PHONY : TemplateField.i

# target to preprocess a source file
TemplateField.cpp.i:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/TemplateField.cpp.i
.PHONY : TemplateField.cpp.i

TemplateField.s: TemplateField.cpp.s

.PHONY : TemplateField.s

# target to generate assembly for a file
TemplateField.cpp.s:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/TemplateField.cpp.s
.PHONY : TemplateField.cpp.s

cc_coin_toss.o: cc_coin_toss.cpp.o

.PHONY : cc_coin_toss.o

# target to build an object file
cc_coin_toss.cpp.o:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/cc_coin_toss.cpp.o
.PHONY : cc_coin_toss.cpp.o

cc_coin_toss.i: cc_coin_toss.cpp.i

.PHONY : cc_coin_toss.i

# target to preprocess a source file
cc_coin_toss.cpp.i:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/cc_coin_toss.cpp.i
.PHONY : cc_coin_toss.cpp.i

cc_coin_toss.s: cc_coin_toss.cpp.s

.PHONY : cc_coin_toss.s

# target to generate assembly for a file
cc_coin_toss.cpp.s:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/cc_coin_toss.cpp.s
.PHONY : cc_coin_toss.cpp.s

cc_udp_test.o: cc_udp_test.cpp.o

.PHONY : cc_udp_test.o

# target to build an object file
cc_udp_test.cpp.o:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/cc_udp_test.cpp.o
.PHONY : cc_udp_test.cpp.o

cc_udp_test.i: cc_udp_test.cpp.i

.PHONY : cc_udp_test.i

# target to preprocess a source file
cc_udp_test.cpp.i:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/cc_udp_test.cpp.i
.PHONY : cc_udp_test.cpp.i

cc_udp_test.s: cc_udp_test.cpp.s

.PHONY : cc_udp_test.s

# target to generate assembly for a file
cc_udp_test.cpp.s:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/cc_udp_test.cpp.s
.PHONY : cc_udp_test.cpp.s

coin_toss_test.o: coin_toss_test.cpp.o

.PHONY : coin_toss_test.o

# target to build an object file
coin_toss_test.cpp.o:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/coin_toss_test.cpp.o
.PHONY : coin_toss_test.cpp.o

coin_toss_test.i: coin_toss_test.cpp.i

.PHONY : coin_toss_test.i

# target to preprocess a source file
coin_toss_test.cpp.i:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/coin_toss_test.cpp.i
.PHONY : coin_toss_test.cpp.i

coin_toss_test.s: coin_toss_test.cpp.s

.PHONY : coin_toss_test.s

# target to generate assembly for a file
coin_toss_test.cpp.s:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/coin_toss_test.cpp.s
.PHONY : coin_toss_test.cpp.s

coin_toss_tester.o: coin_toss_tester.cpp.o

.PHONY : coin_toss_tester.o

# target to build an object file
coin_toss_tester.cpp.o:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/coin_toss_tester.cpp.o
.PHONY : coin_toss_tester.cpp.o

coin_toss_tester.i: coin_toss_tester.cpp.i

.PHONY : coin_toss_tester.i

# target to preprocess a source file
coin_toss_tester.cpp.i:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/coin_toss_tester.cpp.i
.PHONY : coin_toss_tester.cpp.i

coin_toss_tester.s: coin_toss_tester.cpp.s

.PHONY : coin_toss_tester.s

# target to generate assembly for a file
coin_toss_tester.cpp.s:
	$(MAKE) -f CMakeFiles/cointoss.dir/build.make CMakeFiles/cointoss.dir/coin_toss_tester.cpp.s
.PHONY : coin_toss_tester.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cointoss"
	@echo "... GF2_8LookupTable.o"
	@echo "... GF2_8LookupTable.i"
	@echo "... GF2_8LookupTable.s"
	@echo "... TemplateField.o"
	@echo "... TemplateField.i"
	@echo "... TemplateField.s"
	@echo "... cc_coin_toss.o"
	@echo "... cc_coin_toss.i"
	@echo "... cc_coin_toss.s"
	@echo "... cc_udp_test.o"
	@echo "... cc_udp_test.i"
	@echo "... cc_udp_test.s"
	@echo "... coin_toss_test.o"
	@echo "... coin_toss_test.i"
	@echo "... coin_toss_test.s"
	@echo "... coin_toss_tester.o"
	@echo "... coin_toss_tester.i"
	@echo "... coin_toss_tester.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

